apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-connect-operator
  namespace: db-connect-demo

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: db-connect-operator
rules:
- apiGroups: ["db.connect.local"]
  resources: ["postgresqlconnections", "mysqlconnections", "sqliteconnections", "kafkaconnections", "solaceconnections"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["db.connect.local"]
  resources: ["postgresqlconnections/status", "mysqlconnections/status", "sqliteconnections/status", "kafkaconnections/status", "solaceconnections/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["db.connect.local"]
  resources: ["postgresqlconnections/finalizers", "mysqlconnections/finalizers", "sqliteconnections/finalizers", "kafkaconnections/finalizers", "solaceconnections/finalizers"]
  verbs: ["update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: db-connect-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: db-connect-operator
subjects:
- kind: ServiceAccount
  name: db-connect-operator
  namespace: db-connect-demo
